export const TEXTS = {
    TABLE_TITLE: "Assets",
    ACTION_CTA: "Add asset",
    TOTAL: "TOTAL",
    ASSET_TITLE: "Asset name",
    ACCOUNT_TITLE: "Account",
    COST_TITLE: "Initial Value",
    UNITS_TITLE: "Units",
    VALUE_TITLE: "Current Value",
    ARCHIVE_POPUP_TITLE_1: "Archive ",
    ARCHIVE_POPUP_TITLE_2: "?",
    ARCHIVE_POPUP_SUBTITLE: "This historical value of this asset will be preserved until it is permanently deleted from the settings page.",
    ARCHIVE_POPUP_CTA: "Yes, archive",
    ENTRY_BUTTON_DETAILS: "Details",
    ENTRY_BUTTON_ARCHIVE: "Archive",
}