export const FEEDBACK_STRINGS = {
  error: {
    EMAIL: 'Please enter a valid email.',
    PASSWORD: 'Please enter a password with at least 8 characters.',
    TEXT: 'This field is required.',
    NUMBER: 'Please enter a valid number.',
    PHONE: 'Please enter a valid US phone number without a country code.',
    INTEGER: 'Please enter a valid integer.',
    NOT_REQUIRED: 'This field is not required.',
    DATE: 'Please enter a valid date in mm/yyyy format.',
  },
  info: {
    EMAIL: 'Please enter a valid email.',
    PASSWORD: 'Please enter a password with at least 8 characters.',
    TEXT: 'This field is required.',
    NUMBER: 'Please enter a valid number.',
    PHONE: 'Please enter a valid US phone number without a country code.',
    INTEGER: 'Please enter a valid integer.',
    NOT_REQUIRED: 'This field is not required.',
    DATE: 'Please enter a valid date in mm/yyyy format.',
  },
  success: {
    EMAIL: 'Please enter a valid email.',
    PASSWORD: 'Please enter a password with at least 8 characters.',
    TEXT: 'This field is required.',
    NUMBER: 'Please enter a valid number.',
    PHONE: 'Please enter a valid US phone number without a country code.',
    INTEGER: 'Please enter a valid integer.',
    NOT_REQUIRED: 'This field is not required.',
    DATE: 'Please enter a valid date in mm/yyyy format.',
  },
};
