export const TEXTS = {
    TABLE_TITLE: "Assets",
    ACTION_CTA: "Add asset",
    TOTAL: "TOTAL",
    ASSET_TITLE: "Asset name",
    ACCOUNT_TITLE: "Account",
    COST_TITLE: "Initial Value",
    UNITS_TITLE: "Units",
    VALUE_TITLE: "Current Value",
    TYPE_TITLE: "Asset Type",
    DELETE_POPUP_TITLE_1: "Permanently delete ",
    DELETE_POPUP_TITLE_2: "?",
    ARCHIVE_POPUP_TITLE_1: "Archive ",
    ARCHIVE_POPUP_TITLE_2: "?",
    ARCHIVE_POPUP_SUBTITLE: "This historical value of this asset will be preserved until it is permanently deleted or restored from the settings page.",
    DELETE_POPUP_SUBTITLE: "This asset and all historical values will be permanenetly deleted. There is no way to undo this action.",
    ARCHIVE_POPUP_CTA: "Yes, archive",
    DELETE_POPUP_CTA: "Yes, delete",
    ENTRY_BUTTON_DETAILS: "Details",
    ENTRY_BUTTON_ARCHIVE: "Archive",
}