export const TEXTS = {
    TABLE_TITLE: "Assets",
    BTN_DELETE: "Delete",
    TOTAL: "TOTAL",
    ASSET_TITLE: "Asset name",
    ACCOUNT_TITLE: "Account",
    COST_TITLE: "Initial Value",
    UNITS_TITLE: "Units",
    VALUE_TITLE: "Current Value",
    INIT_VALUE_TITLE: "Initial Value",
    TYPE_TITLE: "Asset Type",
    DELETE_POPUP_TITLE_1: "Permanently delete ",
    DELETE_POPUP_TITLE_2: "?",
    DELETE_POPUP_SUBTITLE: "This asset and all historical values will be permanenetly deleted. There is no way to undo this action.",
    DELETE_POPUP_CTA: "Yes, delete",
    ENTRY_BUTTON_DETAILS: "Details",
}